import type { Metadata } from "next";
// Import Montserrat from Google Fonts
import { Montserrat } from "next/font/google";
import "./globals.css";

// Create a variable for Montserrat font
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
